#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FriendWrangler.Resource", IsApplication=true)]

namespace FriendWrangler
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Couchbase.Lite.Android.Resource.String.library_name = global::FriendWrangler.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int darkButtonColor = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int hintColor = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int lightButtonColor = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int mainBackground = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textColor = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int About = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int CreateEvent = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int EventDescription = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int EventHistory = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int EventName = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int PendingEvents = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int SelectFriends = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int SendTestMessage = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateEvent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int FriendWranglerStyle = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int FriendWranglerTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
